---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-eck-secret
  namespace: jaeger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sync-eck-secret
  namespace: jaeger
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-eck-secret
  namespace: jaeger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sync-eck-secret
subjects:
  - name: sync-eck-secret
    namespace: jaeger
    kind: ServiceAccount
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-eck-secret
  namespace: jaeger
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: sync-eck-secret
          containers:
            - name: infra-tester
              command: ["/bin/ash"]
              image: "140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest"
              args: ["-c", "kubectl get secret -o json --namespace eck elasticsearch-es-http-certs-public --export |jq 'del(.metadata.namespace)|del(.metadata.ownerReferences)|del(.metadata.selfLink)|del(.metadata.managedFields)|del(.metadata.creationTimestamp)' | kubectl apply -n jaeger -f -"]
