---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-verify
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: nexusCredentialsSecret
        type: string
        description: Name of secret containing nexus credentials
        default: nexus-credentials
  steps:
    - name: verify
      image: maven:3.6.3-jdk-8-openj9
      workingDir: /workspace/source
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
      env:
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.nexusCredentialsSecret)
              key: username
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.nexusCredentialsSecret)
              key: password
      command: ["mvn"]
      args:
        - "-f"
        - "pom.xml"
        - "-s"
        - "settings.xml"
        - "verify"
        - "-Dci"
  sidecars:
    - image: docker:19.03.6-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-package
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: nexusCredentialsSecret
        type: string
        description: Name of secret containing nexus credentials
        default: nexus-credentials
  workspaces:
    - name: compiled
      description: The workspace we write the jar file to
  steps:
    - name: package
      image: maven:3.6.3-jdk-8-openj9
      workingDir: /workspace/source
      env:
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.nexusCredentialsSecret)
              key: username
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.nexusCredentialsSecret)
              key: password
      command: ["mvn"]
      args:
        - "-f"
        - "pom.xml"
        - "-s"
        - "settings.xml"
        - "package"
        - "-DskipTests"
        - "-DoutputDirectory=$(workspaces.compiled.path)"

# ava-transactions/target is where jar is created

# x Run maven tests
# - Establish version for image
# x Run docker build (in dockerfile creates jar etc) and push docker image to repo
# x Insert version into manifest
# x Push changed manifest back to repo
