apiVersion: v1
data:
  grafana.ini: W2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gdHJ1ZQpvcmdfcm9sZSA9IEFkbWluCltzZXJ2ZXJdCnJvb3RfdXJsID0gaHR0cDovL2dyYWZhbmEuZXhhbXBsZS5jb20vCg==
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
type: Opaque
