apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
  namespace: jaeger
spec:
  endpoints:
  - port: http-metrics
  jobLabel: job
  selector:
    matchLabels:
      name: jaeger-operator
