apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: kafka
spec:
  endpoints:
  - port: tcp-prometheus
  jobLabel: job
  selector:
    matchLabels:
      strimzi.io/name: cluster-kafka-exporter
