---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: nexus
spec:
  rules:
  - host: nexus.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-0
          servicePort: 8081
  tls:
  - hosts:
    - nexus.example.com
    secretName: nexus-tls-secret

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nexus
spec:
  secretName: nexus-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nexus.example.com
  dnsNames:
  - nexus.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx-external
      domains:
      - nexus.example.com
