apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.6
          resources:
            requests:
              memory: "200Mi"
              cpu: 200m
            limits:
              memory: "400Mi"
              cpu: 500m
          args:
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
          volumeMounts:
          - name: redis-data
            mountPath: /data
            subPath: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
