apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
  namespace: kafka
spec:
  kafka:
    version: 2.7.1
    replicas: 3
    listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: 2.7
      auto.create.topics.enable: false
    storage:
      volumes:
      - type: persistent-claim
        size: 15Gi
        id: 0
      type: jbod
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 15Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
