name: Gather dependencies
on:
  pull_request:
    types:
    - opened
    - reopened
    - labeled
    - synchronize
    - edited
    - ready_for_review
    - unlocked
    paths:
    - manifest.yaml
jobs:
  gather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PLATFORM_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PLATFORM_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull infra-tester from ECR
        run: docker pull $ECR_REGISTRY/platform/infra-tester:latest; docker tag $ECR_REGISTRY/platform/infra-tester:latest platform/infra-tester:latest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      - name: Install dependencies
        run: curl -Lo yq https://github.com/mikefarah/yq/releases/download/3.2.0/yq_linux_amd64 && chmod +x yq 
      - name: Gather dependencies from manifest.yaml and commit them to the repo 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_SECRET_TOKEN }}
          HUB_PROTOCOL: https
        run: .github/workflows/gather.sh
