name: Build
on:
  push:
    branches:
      - master
      - noticket/pipeline
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Add JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ secrets.JDK_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run the tests
      env:
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_USERNAME: developer
        MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC
      run: mvn -f pom.xml -s settings.xml verify -ntp -Dci=true -Djib.skip=true
    - name: Notify slack
      uses: innocarpe/actions-slack@v1
      if: ( ! success() )
      with:
        status: ${{ job.status }}
        failure_text: 'Tests failed on ${{ github.repository }} ☠️'
        cancelled_text: 'Tests cancelled on ${{ github.repository }} ✋'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # This job executes the build and will result in a new image
  # being pushed to the ECR repository for this service.
  # The actual image build and push are handled by Maven for this service.
  build:
    runs-on: ubuntu-latest
    name: Build image
    steps:
    - uses: actions/checkout@v2
    - name: Add JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ secrets.JDK_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
## enable as appropriate
# aws
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1
#    - name: Login to Amazon ECR
#      uses: aws-actions/amazon-ecr-login@v1
#    - name: Build and push
#      env:
#        NEXUS_URL: ${{ secrets.NEXUS_URL }}
#        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
#        NEXUS_USERNAME: developer
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC
#      run: mvn -f pom.xml -s settings.xml package -ntp -Dci=true -Dmaven.test.skip -DskipTests
# oci
#    - name: Login to OCR
#      env:
#        OCR_USERNAME: ${{ secrets.OCR_USERNAME }}
#        OCR_PASSWORD: ${{ secrets.OCR_PASSWORD }}
#        OCR_SERVER: xxx.ocir.io
#      run: |
#        docker login xxx.ocir.io -u $OCR_USERNAME -p $OCR_PASSWORD
#        cat /home/runner/.docker/config.json
#    - name: Build and push
#      env:
#        NEXUS_URL: ${{ secrets.NEXUS_URL }}
#        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
#        NEXUS_USERNAME: developer
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC
#      run: mvn clean -Djib.to.auth.username=$OCR_USERNAME -Djib.to.auth.password="$OCR_PASSWORD" -Djib.image.repository="xxx.ocir.io/xxx" -f pom.xml -s .github/settings.xml clean package -ntp -Dci -Dgenerate-docker -Dmaven.test.skip -DskipTests -T10C
## end enable as appropriate
    - name: Notify slack
      uses: innocarpe/actions-slack@v1
      if: ( ! success() )
      with:
        status: ${{ job.status }}
        failure_text: 'Build failed on ${{ github.repository }} ☠️'
        cancelled_text: 'Build cancelled on ${{ github.repository }} ✋'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # This job will update the infra repo with the newly built image tag
  # on the int overlay. It will only create the PR.
  # After the PR is raised the infra repo CI/CD process takes over
  update-manifests:
    name: Update manifests
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: source
    - name: Set the env var 'REPOSITORY_NAME'
      run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
      shell: bash
    - name: Checkout infra repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/infra
        path: infra
        token: ${{ secrets.GH_PAT }}
    - name: Add JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ secrets.JDK_VERSION }}
    - name: Get image tag
      id: image-tag
      env:
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_USERNAME: developer
        MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC
      run: |
        IMAGE_TAG=$(mvn -f source/pom.xml -s source/settings.xml \
        pl.project13.maven:git-commit-id-plugin:revision \
        help:evaluate -Dexpression=jib.image.version.tag -q -DforceStdout)
        [ -z "$IMAGE_TAG" ] && exit 1

        echo "##[set-output name=tag;]$IMAGE_TAG"
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Generate changelog
      id: changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        OCTOCAM_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        REPO_OWNER: ${{ github.repository_owner }}
      working-directory: source
      run: |
        COMMIT_FROM=$(git rev-list --max-parents=0 HEAD)
        PR_FROM=$(date -d "@$(git show -s --format=%ct $COMMIT_FROM)" --iso-8601=seconds)
        PR_TO=$(date --iso-8601=seconds)
        gem install octocam
        octocam -o $REPO_OWNER -r $REPOSITORY_NAME -f $PR_FROM -t $PR_TO > ../CHANGELOG.md
    - uses: imranismail/setup-kustomize@master
      with:
        kustomize-version: "3.9.2"
    - name: Create PR
      env:
        TARGET_ENV: ${{ secrets.CICD_TARGET_ENV }}
        GITHUB_USERNAME: ${{ secrets.GH_BOT_UNAME }}
        GITHUB_EMAIL: ${{ secrets.GH_BOT_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        IMAGE_REGISTRY: ${{ secrets.AWS_ECR_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        APP_VERSION: ${{ steps.image-tag.outputs.tag }}
      run: source/.github/workflows/raise-pr.sh
    # Let's tell slack if this fails.
    - name: Notify slack
      uses: innocarpe/actions-slack@v1
      if: ( ! success() )
      with:
        status: ${{ job.status }}
        success_text: '💯 *successfully* raised `infra` PR for `${{ secrets.CICD_TARGET_ENV }}` overlay for `${{ github.repository }}:${{ steps.image-tag.outputs.tag }}`'
        failure_text: '☠️ *failed* to raise `infra` PR for `${{ secrets.CICD_TARGET_ENV }}` overlay for `${{ github.repository }}:${{ steps.image-tag.outputs.tag }}`'
        cancelled_text: '✋ *cancelled* `infra` PR `${{ secrets.CICD_TARGET_ENV }}` overlay creation for `${{ github.repository }}:${{ steps.image-tag.outputs.tag }}`'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
