name: Test PR
on:
  pull_request:
    branches:
      - master 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV 
      shell: bash
    - name: Add jdk-8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run the tests
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_USERNAME: developer
        MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC
      run: mvn -f pom.xml -s settings.xml verify -ntp -Dci=true -Djib.skip=true
    - name: run debug
      if: ( ! success() )
      run: |
        cat /home/runner/work/$REPOSITORY_NAME/$REPOSITORY_NAME/target/failsafe-reports/*-jvmRun*.dump
        cat /home/runner/work/$REPOSITORY_NAME/$REPOSITORY_NAME/target/failsafe-reports/failsafe-summary.xml
