apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: ALLOW_ANY # REGISTRY_ONLY to block traffic
#  values:
#    global:
#      tracer: # enable for tracing, do not enable if you trace apps directly
#        zipkin:
#          address: stream-collector.jaeger.svc.cluster.local:9411
