---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    k8s-app: cilium
    role.kubernetes.io/networking: "1"
  name: hubble-metrics
  namespace: kube-system
spec:
  ports:
  - port: 9091
    name: metrics
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: cilium 
  sessionAffinity: None
  type: ClusterIP
