apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-metrics
  namespace: kube-system
  labels:
    k8s-app: cilium
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      k8s-app: cilium
