apiVersion: v1
data:
  server-tokens: 'false'
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ingress-nginx-internal
    app.kubernetes.io/part-of: ingress-nginx-internal
  name: nginx-configuration
  namespace: ingress-nginx-internal
