---
apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  name: eck
  namespace: eck
spec:
  version: 7.3.2
  nodeCount: 2
  config:
    rum:
      enabled: true
      allow_origins:
      - '*.example.com'
    setup.template.name: "apm-%{[observer.version]}"
    setup.template.pattern: "apm-%{[observer.version]}-*"
    output:
      elasticsearch:
        indices:
        - index: "apm-%{[observer.version]}-sourcemap"
          when.contains:
            processor.event: "sourcemap"
        - index: "apm-%{[observer.version]}-error-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "error"
        - index: "apm-%{[observer.version]}-transaction-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "transaction"
        - index: "apm-%{[observer.version]}-span-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "span"
        - index: "apm-%{[observer.version]}-metric-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "metric"
        - index: "apm-%{[observer.version]}-onboarding-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "onboarding"
  elasticsearchRef:
    name: eck
  http:
    tls:
      certificate:
        secretName: apm-tls-secret

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eck-apm
  namespace: eck
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - apm.example.com
    secretName: apm-tls-secret
  rules:
  - host: apm.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eck-apm-http
          servicePort: 8200

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: eck-apm
  namespace: eck
spec:
  secretName: apm-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: apm.example.com
  dnsNames:
  - apm.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx-external
      domains:
      - apm.example.com
