---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.2.0
  nodeCount: 2
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      certificate:
        secretName: kibana-tls-secret
    service:
      sessionAffinity: ClientIP
