apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: git
  namespace: concourse-main
secretDescriptor:
  backendType: secretsManager
  data:
    - key: git
      property: key
      name: key
