apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki-output
  namespace: logging-operator
spec:
  loki:
    url: http://platform-loki.loki.svc.cluster.local:3100
    buffer:
      chunk_limit_size: 1M
      flush_mode: interval
      flush_interval: 5s
      flush_thread_count: 4
      overflow_action: block
      retry_forever: true
      timekey: 30s
      timekey_wait: 10s
      timekey_use_utc: true
    extract_kubernetes_labels: true
    labels:
      logHost: "$.logHost"
