apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-flow
  namespace: logging-operator
spec:
  match:
    - select: {}
  filters:
    - tag_normaliser: {}
    - parser:
        key_name: log
        reserve_time: true
        reserve_data: true
        remove_key_name_field: true
        parse:
          type: multi_format
          patterns:
          - format: json
          - format: nginx
          - format: syslog
          - format: apache2
  outputRefs:
    - loki-output
