# N.B. This set of resources assume the existence of two secrets named
# elasticsearch-es-http-certs-public and elasticsearch-es-elastic-user
# containing elasticsearch cert and credentials, respectively.
# They should conform to the format automatically created by ECK.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging-operator
resources:
  - namespace.yaml
  - logging.yaml
  - clusterflow.yaml
  - clusteroutput.yaml
  - logging-operator.yaml
