apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-log
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging-operator
  fluentd:
    metrics:
      serviceMonitor: true
  fluentbit: 
    metrics:
      serviceMonitor: true
