apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-log
spec:
  controlNamespace: logging-operator
  enableRecreateWorkloadOnImmutableFieldChange: true
  fluentbit:
    filterKubernetes:
      K8S-Logging.Parser: "On"
    image:
      repository: fluent/fluent-bit
      tag: 1.7-debug 
    metrics:
      serviceMonitor: true
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  fluentd:
    disablePvc: true
    logLevel: debug
    metrics:
      serviceMonitor: true
    livenessProbe:
      tcpSocket:
        port: 24240
      initialDelaySeconds: 45
      periodSeconds: 20
    readinessProbe:
      tcpSocket:
        port: 24240
      initialDelaySeconds: 45
      periodSeconds: 10
    resources:
      limits:
        cpu: 2000m
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 2Gi
    scaling:
      replicas: 3
