apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-log
spec:
  controlNamespace: logging-operator
  enableRecreateWorkloadOnImmutableFieldChange: true
  fluentbit:
    filterKubernetes:
      K8S-Logging.Parser: "On"
    resources:
      requests:
        cpu: 200m
        memory: 500M
      limits:
        cpu: 600m
        memory: 1Gi
    metrics:
      serviceMonitor: true
  fluentd:
    resources:
      requests:
        cpu: 200m
        memory: 500M
      limits:
        cpu: 600m
        memory: 1Gi
    scaling:
      replicas: 3
    metrics:
      serviceMonitor: true
