# This will automatically merge the int PR raised by the application if checks are passed and will raise a PR or modify the current PR to merge development to qa
name: Integration deployment workflow
on:
  pull_request:
    paths:
    - 'k8s/int/kustomization.yaml'
    types:
    - opened
    - reopened
    - edited
    - ready_for_review
    - unlocked
    - labeled
    - unlabeled
jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'release/int') &&
        contains('fakeci', github.event.pull_request.user.login) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: jq '.' "$GITHUB_EVENT_PATH" 
    - run: |
        .github/workflows/rebase.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    - uses: geertvdc/setup-hub@master
    - uses: imranismail/setup-kustomize@master
      with:
        kustomize-version: "3.6.1"
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Merge PR
      env:
        GITHUB_USER: fakeci
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        OCTOCAM_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        IN_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPO: ${{ github.repository }}
        IN_PR_ENV: int
        OUT_PR_ENV: qa
      run: |
        gem install octocam
        curl -Lo /tmp/yq https://github.com/mikefarah/yq/releases/download/3.2.0/yq_linux_amd64 && chmod +x /tmp/yq 
        .github/workflows/pr-wrangler.sh
    - name: Notify slack
      uses: innocarpe/actions-slack@v1
      if: always()
      with:
        status: ${{ job.status }}
        success_text: '💯 *successfully* raised/updated PR for `int`'
        failure_text: '☠️ *failed* PR for `int`'
        cancelled_text: '✋ *cancelled* PR for `int`'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INT }}
