---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
    - aws-privateca-issuer.yaml
    - chart/crds/awspca.cert-manager.io_awspcaclusterissuers.yaml
    - chart/crds/awspca.cert-manager.io_awspcaissuers.yaml
