---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: infra-git
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:11FSConsulting/platform.git

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: apply-kustomize-manifests
  namespace: tekton-pipelines
spec:
  resources:
    - name: source
      type: git
  params:
    - name: pathToK8sDir
      description: The path to base kustomize directory in repo
      default: k8s
  tasks:
  - name: k8s-kustomize
    taskRef:
      name: k8s-kustomize
    params:
      - name: pathToK8sDir
        value: "$(params.pathToK8sDir)"
    resources:
      inputs:
        - name: source
          resource: source
