# Default values for logging-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/banzaicloud/logging-operator 
  tag: 3.9.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

annotations: {}

## Deploy CRDs used by Logging Operator.
##
createCustomResource: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

http:
  # http listen port number
  port: 8080
  # Service definition for query http service
  service:
    type: ClusterIP
    clusterIP: None
    # Annotations to query http service
    annotations: {}
    # Labels to query http service
    labels: {}

rbac:
  enabled: true
  psp:
    enabled: false

## SecurityContext holds pod-level security attributes and common container settings.
## This defaults to non root user with uid 1000 and gid 2000.	*v1.PodSecurityContext	false
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
podSecurityContext:
 runAsNonRoot: true
 runAsUser: 1000
 fsGroup: 2000
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

## Operator priorityClassName
##
priorityClassName: {}

monitoring:
  # Create a Prometheus Operator ServiceMonitor object
  serviceMonitor:
    enabled: true
