apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: tekton-pipelines
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 500
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
              - wget
              - --spider
              - el-cron-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: Never
