apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: eck
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    rum:
      allow_origins:
      - '*.example.com'
    ilm:
      enabled: "auto"
      setup:
        mapping:
        - event_type: "error"
          policy_name: "apm-error-span-policy"
        - event_type: "span"
          policy_name: "apm-error-span-policy"
        - event_type: "transaction"
          policy_name: "apm-transaction-metric-policy"
        - event_type: "metric"
          policy_name: "apm-transaction-metric-policy"
        enabled: "true"
        overwrite: "true"
      policies:
        - name: "apm-error-span-policy"
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "50gb"
                    max_age: "1d"
                  set_priority:
                    priority: 100
              warm:
                min_age: "7d"
                actions:
                  set_priority:
                    priority: 50
                  readonly: {}
              cold:
                min_age: "30d"
                actions:
                  set_priority:
                    priority: 0
                  freeze: {}
              delete:
                min_age: "60d"
                actions:
                  delete: {}
        - name: "apm-transaction-metric-policy"
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_size: "50gb"
                    max_age: "30d"
                  set_priority:
                    priority: 100
              warm:
                min_age: "60d"
                actions:
                  set_priority:
                    priority: 50
                  readonly: {}
              cold:
                min_age: "90d"
                actions:
                  set_priority:
                    priority: 0
                  freeze: {}
  http:
    tls:
      certificate:
        secretName: apm-tls-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apm
  namespace: eck
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - apm.example.com
    secretName: apm-tls-secret
  rules:
  - host: apm.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apm-apm-http
          servicePort: 8200
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apm
  namespace: eck
spec:
  secretName: apm-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: apm.example.com
  dnsNames:
  - apm.example.com
