apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: eck
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      certificate:
        secretName: apm-tls-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apm
  namespace: eck
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - apm.example.com
    secretName: apm-tls-secret
  rules:
  - host: apm.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apm-http
          servicePort: 8200
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apm
  namespace: eck
spec:
  secretName: apm-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: apm.example.com
  dnsNames:
  - apm.example.com
