name: Build & Push 
on:
  push:
    paths:
      - 'components/infra-tester/Dockerfile'
      - '.github/workflows/build_image_gcp.yaml'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: project-peach-development/infra-tester
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: us.gcr.io 
        workdir: components/infra-tester
