name: Build & Push 
on:
  push:
    paths:
      - 'images/infra-tester/Dockerfile'
    branches:
      - master
      - new_workflows
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PLATFORM_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PLATFORM_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag & push image
        run: docker build -t "${REGISTRY}/${IMAGE}:${GITHUB_SHA:0:5}" "${DIRECTORY}"; docker tag "${REGISTRY}/${IMAGE}:${GITHUB_SHA:0:5}" "${REGISTRY}/${IMAGE}:latest"; docker push "${REGISTRY}/${IMAGE}"
        env:
          DIRECTORY: images/infra-tester 
          IMAGE: platform/infra-tester
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
