name: Lint & verify 
on:
  pull_request:
    branches:
      - master
jobs:
  check_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint and verify code
        run: docker build components/infra-tester -t test-infra && docker run -v `pwd`:/workspace -t test-infra
