name: Lint & verify 
on:
  pull_request:
    branches:
      - master
jobs:
  check_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pull infra-tester from ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_PLATFORM_ECR_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_PLATFORM_ECR_SECRET_ACCESS_KEY }}
          region: eu-west-2
          image: platform/infra-tester:latest
          local-image: platform/infra-tester
          direction: pull
      - name: Lint and verify code
        run: docker run -v `pwd`:/workspace -t platform/infra-tester 
