name: Lint & verify 
on:
  pull_request:
    branches:
      - master
jobs:
  check_package:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PLATFORM_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PLATFORM_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v1
      - name: Pull infra-tester from ECR
        run: docker pull $ECR_REGISTRY/platform/infra-tester:latest; docker tag $ECR_REGISTRY/platform/infra-tester:latest platform/infra-tester:latest
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      - name: Lint and verify code
        run: docker run -v `pwd`:/workspace -t platform/infra-tester 
