---
namespace: tekton-pipelines
resources:
- pipelines.yaml
- dashboard.yaml
- triggers.yaml
- rbac.yaml
- dashboard-ingress.yaml
- webhook.yaml
- pipeline-kustomize.yaml 
- pipeline-terraform.yaml
- git-clone.yaml
- tekton-cleaner.yaml
