---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: infra-cd
spec:
  params:
  - name: git-revision
    description: The git revision
    default: master
  - name: git-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: infra-cd-
    spec:
      serviceAccountName: infra-build-bot
      pipelineRef:
        name: infra-cd
      params:
      - name: git-url
        value: $(tt.params.git-url) 
      - name: git-revision
        value: $(tt.params.git-revision)
      workspaces:
        - name: git-source
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: infra-cd
spec:
  params:
  - name: kustomizeDir
    description: The path to the kustomize dir we're applying, relative to repo root
    default: k8s/sandbox
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/11fsconsulting/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
  workspaces:
    - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
      - name: output
        workspace: git-source
  - name: apply-k8s
    runAfter: [fetch-from-git]
    taskRef:
      name: kustomize-apply
      kind: ClusterTask
    params:
    - name: kustomizeDir
      value: "$(params.kustomizeDir)"
    workspaces:
      - name: source
        workspace: git-source
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kustomize-apply
spec:
  workspaces:
    - name: source
  params:
    - name: kustomizeDir
      type: string
      description: Path to the kustomize dir to apply relative to repo root
      default: k8s/dev
  steps:
    - name: k8s-dry-run
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest
      workingDir: $(workspaces.source.path) 
      command: ["/bin/ash"]
      args:
        - "-c"
        - "kustomize build $(inputs.params.kustomizeDir) | kubectl apply -f - --dry-run"
    - name: k8s-apply
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest 
      workingDir: $(workspaces.source.path)
      command: ["/bin/ash"]
      args:
        - "-c"
        - "kustomize build $(inputs.params.kustomizeDir) | kubectl apply -f -"
