---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: terraform-cd
spec:
  params:
  - name: git-revision
    description: The git revision
    default: master
  - name: git-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: terraform-cd-
    spec:
      serviceAccountName: infra-build-bot
      pipelineRef:
        name: terraform-cd
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      workspaces:
        - name: git-source
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terraform-cd
spec:
  params:
  - name: terraformDir
    description: The path to the terraform dir we're applying, relative to repo root
    default: terraform/sandbox
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/11fsconsulting/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
  workspaces:
    - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
      - name: output
        workspace: git-source
  - name: apply-tf
    runAfter: [fetch-from-git]
    taskRef:
      name: terraform-apply
      kind: ClusterTask
    params:
    - name: terraformDir
      value: "$(params.terraformDir)"
    workspaces:
      - name: source
        workspace: git-source
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: terraform-apply
spec:
  workspaces:
    - name: source
  params:
    - name: terraformDir
      type: string
      description: Path to the terraform dir to apply relative to repo root
      default: terraform/sandbox
  steps:
    - name: tf-dry-run
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest
      workingDir: $(workspaces.source.path) 
      command: ["/bin/ash"]
      envFrom:
        - secretRef:
            name: terraform-secrets
      args:
        - "-c"
        - "cd $(inputs.params.terraformDir) && terraform init && terraform validate && tflint --module --deep --loglevel=info && terraform plan"
    - name: tf-apply
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest 
      workingDir: $(workspaces.source.path)
      command: ["/bin/ash"]
      envFrom:
        - secretRef:
            name: terraform-secrets
      args:
        - "-c"
        - "cd $(inputs.params.terraformDir) && terraform init && terraform apply -auto-approve"
