---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: kops-cd
spec:
  params:
  - name: git-revision
    description: The git revision
    default: master
  - name: git-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: kops-cd-
    spec:
      serviceAccountName: build-bot
      pipelineRef:
        name: kops-cd
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision) 
      workspaces:
        - name: git-source
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kops-cd
spec:
  params:
  - name: kopsFile
    description: The path to the kops file we're applying, relative to repo root
    default: k8s/sandbox.yaml
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/11fsconsulting/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
  workspaces:
    - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
      - name: output
        workspace: git-source
  - name: apply-kops
    runAfter: [fetch-from-git]
    taskRef:
      name: kops-apply
      kind: ClusterTask
    params:
    - name: kopsFile
      value: "$(params.kopsFile)"
    - name: git-revision
      value: "$(tasks.fetch-from-git.results.commit)" 
    workspaces:
      - name: source
        workspace: git-source
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kops-apply
spec:
  workspaces:
    - name: source
  params:
    - name: kopsFile
      type: string
      description: Path to the kops dir to apply relative to repo root
      default: kops/sandbox
    - name: git-revision
      type: string
      description: Git ref or tag to apply
  steps:
    - name: kops-dry-run
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest
      workingDir: $(workspaces.source.path) 
      command: ["/bin/ash"]
      envFrom:
        - secretRef:
            name: kops-secrets
      args:
        - "-c"
        - "kops get cluster -o yaml > kops-cluster-prev.yaml && kops replace cluster -f $(inputs.params.kopsFile) && kops update cluster; kops replace cluster -f kops-cluster-prev.yaml"
    - name: kops-apply
      image: 140554600707.dkr.ecr.eu-west-2.amazonaws.com/platform/infra-tester:latest 
      workingDir: $(workspaces.source.path)
      command: ["/bin/ash"]
      envFrom:
        - secretRef:
            name: kops-secrets
      args:
        - "-c"
        - "kops export kubecfg --admin && kops replace cluster -f $(inputs.params.kopsFile) && kops update cluster --yes && kops rolling-update cluster --yes"
