---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kustomize-apply
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToK8sDir
        type: string
        description: Path to the base kustomize directory within the repo
        default: .deployment/k8s
  steps:
    - name: k8s-dry-run
      image: lachlanevenson/k8s-kubectl:v1.17.2
      workingDir: /workspace/source
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - $(inputs.params.pathToK8sDir)
        - "--dry-run"
    - name: k8s-apply
      image: lachlanevenson/k8s-kubectl:v1.17.2
      workingDir: /workspace/source
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - $(inputs.params.pathToK8sDir)

---
apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: source-to-image
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToContext
        description: The path to the build context within the repo
        default: .
      - name: pathToDockerFile
        description: The path to the dockerfile to build within the repo
        default: Dockerfile
      - name: imageUrl
        description: URL of docker repository to push the built image to
      - name: imageTag
        description: Tag to apply to the built image
        default: "latest"
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)
        - --context=/workspace/source/$(inputs.params.pathToContext)
